### ISSUE TITLE
Clarify application experience question on the final application

### ISSUE THREAD

**Issue by JuliaLawall** [outreachy/website#298]
For the question that the mentors see as "Their experience with this free software community and project:", the applicants always seem to say things like "The mentors are really helpful".  Is that what the question is intended to ask?  Or is it intended to ask, eg whether they use the software in their daily life, have they contributed to it before, etc?

I can see both interpretations, but "The mentors are really helpful" is not that useful as an answer, because if the mentors were not helpful, they would probably not be applying in the first place.

**Comment by sagesharp** [comment]
The question has been carried forward since before I started with Outreachy. :) I believe the original question was "Please describe your experience working with this and other free software communities".

We then broke it up into two questions:
 * "Please describe your experience with this free software community and project as a user and as a contributor."
 * "Please describe your experience with any other free software projects as a user and as a contributor."

What the first question is looking for is whether the person has used or contributed to the project before the Outreachy application period. Maybe they've been running Linux user groups or answering questions about the Linux kernel on stack overflow. This question gives them an opportunity to talk about the non-technical ways they've interacted with the community. Unfortunately, if this application period is the first time a person has contributed to a community, the answers tend to look fairly generic.

Although from an organizer perspective, I do sometimes see answers that are an interesting insight into the applicant's experience during the contribution period. Sometimes the vagueness of the question prompts the applicants to talk about previous times they applied to the Outreachy program, and how they improved from last round. Sometimes they mention that they continued contributing to the community even after they weren't accepted, which shows they're passionate about the community.

I agree the question could be re-worded, but I'm sort of reluctant to change it. If you have a suggestion for what it should be changed to, let me know. We could change it to:

"Please describe your experience with this free software community and project as a user and as a contributor **outside of the Outreachy application process**"

**Comment by JuliaLawall** [comment]
On Wed, 10 Apr 2019, Sage Sharp wrote:

>
> The question has been carried forward since before I started with Outreachy.
> :) I believe the original question was "Please describe your experience
> working with this and other free software communities".

Could it be "Please describe your prior experience..."?

It could be good to get feedback on how things went during the application
period, but pehaps the application is not the place where the applicant
would be most honest about that.  Outreachy could send out a survey after
the internships have been decided but before they have been announced, so
that everyone knows that there is no penalty for complaining, but no one
is yet disappointed.

thanks,
julia

**Comment by sagesharp** [comment]
How about this:

"Please describe your experience before this Outreachy application period with this free software community. You can describe your prior experiences as both a user and a contributor."

**Comment by JuliaLawall** [comment]
On Thu, 11 Apr 2019, Sage Sharp wrote:

>
> How about this:
>
> "Please describe your experience before this Outreachy application period
> with this free software community. You can describe your prior experiences
> as both a user and a contributor."

It seems very clear.  Thanks!

julia

**Comment by sagesharp** [comment]
Ok, I'm tagging this as "help wanted" so that it can be a newcomer issue during the PyCon U.S. code sprints.

There are two fields in `class FinalApplication` in `home/models.py` that need to be modified.

Modify the help_text for the `experience` field to be "Please describe your experience before this Outreachy application period with this free software community. You can describe your prior experiences as both a user and a contributor." Modify the verbose_name to be "Past experience with this community."

Modify the help_text for the `foss_experience` field to be "Please describe your experience before this Outreachy application period with any other free software communities. You can describe your prior experiences as both a user and a contributor." Modify the verbose_name to be "Past experience with other communities."

Since you're modifying field verbose names and help text, you'll need to make a migration. [Instructions for making a migration are in the README](https://github.com/sagesharp/outreachy-django-wagtail#migrations)

**Comment by sagesharp** [comment]
In order to test your changes, you'll need to:

 * [Make a new round with the contribution period open](https://github.com/sagesharp/outreachy-django-wagtail#setting-up-a-new-internship-round), following the instructions in README.md.
 * [Create a coordinator account under a new community](https://github.com/sagesharp/outreachy-django-wagtail#coordinatorapproval-class).
 * [Create a Participation object](https://github.com/sagesharp/outreachy-django-wagtail#participation-and-sponsorship-classes) that has the community participating in the newly created round.
 * [Create a project under the community with a mentor](https://github.com/sagesharp/outreachy-django-wagtail#project-and-mentorapproval-classes).
 * [Create an applicant with an ApplicantApproval and Contribution to this project](https://github.com/sagesharp/outreachy-django-wagtail#creating-applicantapproval-test-objects)

Then test how the final application question looks to an applicant. Log in as the applicant. Go to your dashboard `localhost:8000/dashboard`. You should see a prompt to create a final application for the project. Do so, and double check that the final application question and help text look correct.

Next, log in as the project mentor. Go to your dashboard. You should see a prompt to review applicants for your project. Click that link, and make sure the final application question looks correct.

If you log in as the mentor and go to `localhost:8000/dashboard`, you should see a notification to review applicants to your project. If you click the details link for one of the applicants, you'll see the template text that needs to be changed.

**Comment by KunyiLiu** [comment]
Working on it today.
