### ISSUE TITLE
Error during template rendering in homepage

### ISSUE THREAD

**Issue by Aju100** [outreachy/website#366]
Description:
I am not able to render the template.

To reproduce :
- clone the repo
- follow the instructions
- run python3 manage.py runserver
- see the error
![website not rendering](https://user-images.githubusercontent.com/29862610/73048058-05219d80-3ea0-11ea-91f3-50b8429900cf.png)

latest commit: 5a4bc27670d941ee5719e2509403e39c0af3d1db
System : Ubuntu 19.x
Python Version : 3.7.3

**Comment by sagesharp** [comment]
The home page isn't actually in the Outreachy website repository. It's stored in the content management system (CMS) database on the live site. So it's expected that the home page doesn't show anything interesting when you're developing locally.

Feel free to update the README.md to reflect that you may not see the same content on the homepage as on the live site.

That said, the error you're getting about missing postcss is because you're running the management command to start the Django webserver without passing it the node modules installation path. You need to run this command instead:

```
PATH="$PWD/node_modules/.bin:$PATH" ./manage.py runserver
```

You're missing the PATH part of the command. postcss is a node module that the Django webserver needs to find a binary to run. If you don't specify where your node models are installed, Django will throw that error.

The README.md talks about running the web server under the "Testing the Website" section. That section could probably be moved up before the section about using the Django shell, since most beginners will want to know how to view the website first. Feel free to submit a patch to update the README.md.

**Comment by Aju100** [comment]
@sagesharp  thank you so much.
