### ISSUE TITLE
Outreachy email #9 currently references travel stipend despite being on pause d/t coronavrius

### ISSUE THREAD

**Issue by ViolanteCodes** [outreachy/website#459]
Filing bug after suggestion on zulip chat. At current, outreachy applicants are receiving their travel stipend as already budgeted into their stipend, but Outreachy email #9 makes references filing for the travel stipend, which is not valid for this round.

**Comment by sagesharp** [comment]
Documenting this bug more:

# Background

There is text in an automated email to interns that references the Outreachy travel stipend. The Outreachy travel stipend no longer exists.

Outreachy used to pay interns a $5,500 internship stipend and a $500 travel stipend. Since the COVID-19 pandemic hit, we suspended the travel stipend indefinitely. We moved the $500 travel stipend into the internship stipend. Now interns are paid a $6,000 internship stipend.

# Making changes

The week 9 email needs to be edited to encourage mentors to talk to their interns about what online conferences they could attend. The email should not mention the Outreachy travel stipend.

The template for the email to Outreachy interns that is sent during week 9 of the internship is in [home/templates/home/email/internship-week-9.txt](home/templates/home/email/internship-week-9.txt)

# Testing changes

Once you've made edits to the email, you will need to test that the website will send the emails correctly. That involves three steps:

1. Setting up your local website to have an internship round where today's date is during week 9 of the internship.
2. Logging in as an Outreachy organizer on your local website
3. Testing sending the week 9 email

## Setting up the local website

[Follow the instructions in the README](https://github.com/outreachy/website#scenario-7-internship-week-n) to set up an internship cohort at the beginning of week 9:

```
$ ./manage.py shell
>>> from home import scenarios
>>> scenario = scenarios.InternshipWeekScenario(week=9)
```

It's good to [read the explanation](https://github.com/outreachy/website#scenario-7-internship-week-n) of what database objects this code creates. The objects that it creates that will help us solve this bug are objects related to interns and mentors. We'll need those database objects to have interns to send the week 9 email to.

## Logging in

Go to a browser window, and go to the login page: [http://localhost:8000/login/?next=/apply/eligibility/](http://localhost:8000/login/?next=/apply/eligibility/)

Log in using the superuser username and password you picked when you ran the `createsuperuser` command.

Why do you need to log in as the superuser? All Django "superusers" have a special permission called "staff permission". The Outreachy website assumes that anyone with the "staff" permission is an Outreachy organizer.

The website gives Outreachy organizers more access to the website than other users. Only Outreachy organizers can see specific pages, and do specific actions. That includes access to sending semi-automated emails to interns.

So you will need to log in as an Outreachy organizer in order to test the changes to your emails. You can log in as the superuser, which has the staff permission set that will give us access to Outreachy organizer actions.

## Testing the week 9 email

Go to the dashboard on your localhost: [http://localhost:8000/dashboard/](http://localhost:8000/dashboard/). There should be a prompt to send the week 9 emails. Click that button. You will be taken to a preview of the emails you are about to send. Verify the emails look correct.

You may be worried about sending emails accidentally to a random email address. Don't worry, your local copy of the Outreachy website will never send emails. Instead, it will print the emails to a log file.

When the website is running on localhost, it is in Django "debug mode". In debug mode, emails are not sent out. Instead, emails are printed out to the log that is generated by the webserver (i.e. the log that's visible after you run `PATH="$PWD/node_modules/.bin:$PATH" ./manage.py runserver`).

Click the button to send the week 9 emails. Look at your terminal tab where the local webserver is running. You should see the same emails printed to the log. Those printed emails are exactly what would be sent out to applicants. Verify your changes are correct.
